# Generated by Django 5.2.17 on 2026-09-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('telebirr', 'Telebirr')], db_index=True, max_length=20)),
                ('transaction_id', models.CharField(db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=20)),
                ('raw_message', models.TextField(blank=True, help_text='Original Telebirr SMS or webhook payload')),
                ('message_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('merchant_account', models.CharField(blank=True, max_length=100)),
                ('sender_info', models.CharField(blank=True, max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'received_at'], name='payments_pa_user_id_907900_idx'), models.Index(fields=['status', 'provider'], name='payments_pa_status_eb2eec_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'transaction_id'), name='unique_provider_transaction_id')],
            },
        ),
    ]
