# Generated by Django 5.2.17 on 2026-09-30 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_discount_amount_payment_discount_percentage_and_more'),
        ('subscriptions', '0002_subscription_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='binance_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Binance transaction or bizId identifier', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Binance Pay web checkout URL', max_length=512),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_trade_no',
            field=models.CharField(blank=True, db_index=True, help_text='Unique merchant trade number for Binance Pay order tracking', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_expire_time',
            field=models.DateTimeField(blank=True, help_text='Order expiration datetime', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='prepay_id',
            field=models.CharField(blank=True, db_index=True, help_text='Binance Pay prepay identifier', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Binance Pay QR code image URL', max_length=512),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_content',
            field=models.TextField(blank=True, help_text='Raw QR code payload for scanning'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('telebirr', 'Telebirr'), ('binance', 'Binance Pay')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant_trade_no'], name='payments_pa_merchan_312fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['prepay_id'], name='payments_pa_prepay__d08a87_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant_trade_no__isnull', False)), fields=('merchant_trade_no',), name='unique_binance_merchant_trade_no'),
        ),
    ]
