# Generated by Django 5.2.17 on 2026-10-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_binance_order_id_payment_checkout_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('telebirr', 'Telebirr'), ('binance', 'Binance Pay')], db_index=True, max_length=20),
        ),
    ]
