# Generated by Django 5.2.17 on 2026-10-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_provider'),
        ('subscriptions', '0002_subscription_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceManualPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable Binance Manual Payment on checkout')),
                ('receiving_identifier', models.CharField(default='123456789', help_text='Receiving Binance Pay ID, Binance UID, or wallet address', max_length=128)),
                ('receiving_identifier_type', models.CharField(choices=[('PAY_ID', 'Binance Pay ID'), ('UID', 'Binance UID'), ('USDT_TRC20', 'USDT (TRC-20 Address)'), ('USDT_BEP20', 'USDT (BEP-20 Address)'), ('OTHER', 'Other Identifier / Address')], default='PAY_ID', help_text='Type of identifier provided to the customer', max_length=32)),
                ('qr_code', models.ImageField(blank=True, help_text='Optional QR code image for customer scanning', null=True, upload_to='payments/qr/')),
                ('payment_instructions', models.TextField(blank=True, default='1. Open your Binance app or web portal.\n2. Send the exact required amount to our configured Binance identifier above.\n3. Obtain your transaction ID (or order ID / TxID) and Note your sender Binance UID.\n4. Return to Humatron and submit the transaction information below.\n5. A Humatron administrator will verify the receipt and activate your subscription.', help_text='Clear step-by-step payment instructions for users.')),
                ('support_message', models.TextField(blank=True, default='Need assistance with your transfer? Contact support@humatron.me with your transaction reference.', help_text='Support contact message displayed to the user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Binance Manual Payment Settings',
                'verbose_name_plural': 'Binance Manual Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='BinanceManualPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Binance Manual Payment',
                'verbose_name_plural': 'Binance Manual Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes by administrator'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BINANCE_MANUAL', 'Binance Manual Payment'), ('BINANCE_PAY_API', 'Binance Pay API (Automated)'), ('TELEBIRR', 'Telebirr Manual SMS'), ('OTHER', 'Other')], db_index=True, default='BINANCE_MANUAL', help_text='Extensible payment method abstraction', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Optional payment screenshot or proof document', null=True, upload_to='payments/proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When administrator approved or rejected the payment', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who reviewed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_identifier',
            field=models.CharField(blank=True, help_text='Sender Binance UID or identifier', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When user submitted the manual payment information', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('RECEIVED', 'Received'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_11cbdd_idx'),
        ),
    ]
