# Generated by Django 5.2.17 on 2026-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_binancemanualpaymentsettings_binancemanualpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student_discount_applied',
        ),
        migrations.AlterField(
            model_name='binancemanualpaymentsettings',
            name='receiving_identifier',
            field=models.CharField(default='1104715375', help_text='Receiving Binance Pay ID, Binance UID, or wallet address', max_length=128),
        ),
        migrations.AlterField(
            model_name='binancemanualpaymentsettings',
            name='receiving_identifier_type',
            field=models.CharField(choices=[('PAY_ID', 'Binance Pay ID'), ('UID', 'Binance UID'), ('USDT_TRC20', 'USDT (TRC-20 Address)'), ('USDT_BEP20', 'USDT (BEP-20 Address)'), ('OTHER', 'Other Identifier / Address')], default='UID', help_text='Type of identifier provided to the customer', max_length=32),
        ),
    ]
