# Generated by Django 5.2.17 on 2026-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelebirrPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable Telebirr payments for Ethiopian users')),
                ('receiver_name', models.CharField(default='Humatron Technologies', help_text='Receiver / Merchant Name displayed to customers for Telebirr transfer', max_length=150, verbose_name='Name')),
                ('phone_number', models.CharField(default='0911000000', help_text='Telebirr phone number where customers send payment', max_length=50, verbose_name='Phone Number')),
                ('instructions', models.TextField(blank=True, default='1. Open your Telebirr app or dial *127#.\n2. Transfer the exact plan amount to our Telebirr Phone Number and Name above.\n3. Upon completion, enter your Telebirr transaction number below.', help_text='Payment instructions displayed to Ethiopian customers.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telebirr Payment Settings',
                'verbose_name_plural': 'Telebirr Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='TelebirrPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Telebirr Payment',
                'verbose_name_plural': 'Telebirr Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
    ]
