# Generated by Django 5.2.17 on 2026-09-27 11:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('country', models.CharField(choices=[('Ethiopia', 'Ethiopia'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('South Africa', 'South Africa'), ('Egypt', 'Egypt'), ('India', 'India'), ('China', 'China'), ('Japan', 'Japan'), ('Australia', 'Australia'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('United Arab Emirates', 'United Arab Emirates'), ('Other', 'Other Country')], default='Ethiopia', max_length=100, verbose_name='Country')),
                ('job_title', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Developer', 'Developer'), ('Researcher', 'Researcher'), ('Business Owner', 'Business Owner'), ('Administrator', 'Administrator'), ('Other', 'Other')], default='Developer', max_length=64, verbose_name='Job Title')),
                ('job_title_other', models.CharField(blank=True, max_length=100, verbose_name='Job Title (Other)')),
                ('sex', models.CharField(choices=[('prefer_not_to_say', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='prefer_not_to_say', max_length=32, verbose_name='Sex')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('trial_used', models.BooleanField(default=False, verbose_name='Free Trial Consumed')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Device Identifier Hash')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTrialSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('trials_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['device_fingerprint'], name='accounts_us_device__942cb2_idx'),
        ),
    ]
