# Generated by Django 5.2.17 on 2026-09-27 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedEducationalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Domain name without @ (e.g. aau.edu.et, mit.edu, oxford.ac.uk)', max_length=128, unique=True)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Educational Email Address')),
                ('educational_domain', models.CharField(blank=True, max_length=128)),
                ('educational_email_verified', models.BooleanField(default=False)),
                ('student_id_file', models.FileField(blank=True, help_text='Uploaded Student ID document (JPG, PNG, PDF)', upload_to='private/student_ids/')),
                ('student_id_expiration_date', models.DateField(blank=True, help_text='Expiration date indicated on the student ID card', null=True, verbose_name='Student ID Expiration Date')),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Educational Email Verification'), ('EMAIL_VERIFIED', 'Educational Email Verified'), ('UNDER_REVIEW', 'Under Administrator Review'), ('VERIFIED', 'Verified Student (25% Discount Active)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired Student ID')], db_index=True, default='NOT_SUBMITTED', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_st_status_3dda5e_idx'), models.Index(fields=['educational_email'], name='accounts_st_educati_847e20_idx')],
            },
        ),
    ]
