# Generated by Django 5.2.17 on 2026-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_approvededucationaldomain_studentverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentverification',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Educational Institution'),
        ),
    ]
