# Generated by Django 5.2.17 on 2026-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentverification_educational_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedEducationalDomain',
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Developer', 'Developer'), ('Researcher', 'Researcher'), ('Business Owner', 'Business Owner'), ('Administrator', 'Administrator'), ('Other', 'Other')], default='Developer', max_length=64, verbose_name='Job Title'),
        ),
        migrations.DeleteModel(
            name='StudentVerification',
        ),
    ]
