# Generated by Django 5.2.17 on 2026-09-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_disabled', 'Admin Disabled User'), ('user_enabled', 'Admin Enabled User'), ('user_verified', 'Admin Manually Verified Email'), ('subscription_changed', 'Admin Changed Subscription'), ('plan_modified', 'Admin Modified Plan'), ('payment_reviewed', 'Admin Manually Reviewed Payment'), ('payment_status_changed', 'Admin Changed Payment Status'), ('document_deleted', 'Admin Deleted Document'), ('other', 'Other Action')], max_length=64)),
                ('target', models.CharField(help_text='Resource or identifier targeted', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['target'], name='audit_audit_target_972e41_idx')],
            },
        ),
    ]
