# Generated by Django 5.2.17 on 2026-09-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_etb', models.DecimalField(decimal_places=2, default=6750.0, help_text='Explicit Telebirr price in Ethiopian Birr (Sec 31)', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('pdf_limit', models.PositiveIntegerField(default=25, help_text='Total PDFs allowed in this plan period')),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum upload size in Megabytes')),
                ('max_pages_per_pdf', models.PositiveIntegerField(default=200, help_text='Maximum pages per document')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pdf_limit', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=32)),
                ('is_notified_expiring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx')],
            },
        ),
    ]
