# Generated by Django 5.2.17 on 2026-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='student_discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_etb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Explicit Telebirr price in Ethiopian Birr, configured by administrator (Sec 1)', max_digits=10, null=True),
        ),
    ]
