# Generated by Django 5.2.17 on 2026-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='student_discount_applied',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_file_size_mb',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_pages_per_pdf',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pdf_limit',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(default='month', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of feature bullet points for the pricing card'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_file_size',
            field=models.PositiveIntegerField(default=50, help_text='Maximum upload size in Megabytes (MB)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='processing_priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Higher than Free', 'Higher than Free'), ('High', 'High'), ('Highest', 'Highest')], default='Normal', help_text='Processing priority tier', max_length=50),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='subscriptionplan',
                    name='slug',
                    field=models.SlugField(default='', unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE subscriptions_subscriptionplan ADD COLUMN slug varchar(50) DEFAULT '';
                    UPDATE subscriptions_subscriptionplan SET slug = code WHERE slug = '' OR slug IS NULL;
                    CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_subscriptionplan_slug_key ON subscriptions_subscriptionplan(slug);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS subscriptions_subscriptionplan_slug_key;
                    ALTER TABLE subscriptions_subscriptionplan DROP COLUMN IF EXISTS slug;
                    """,
                ),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='usage_limit',
            field=models.PositiveIntegerField(default=50, help_text='Total PDFs allowed per billing period (0 denotes unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pdf_limit',
            field=models.PositiveIntegerField(help_text='0 denotes unlimited'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SlugField(blank=True, help_text='Legacy alias for slug', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_etb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional Telebirr price in Ethiopian Birr, configured by administrator', max_digits=10, null=True),
        ),
    ]
