# Generated by Django 5.2.17 on 2026-09-27 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(help_text='Randomized server filename in uploads/', max_length=255)),
                ('processed_filename', models.CharField(blank=True, help_text='Randomized server filename in processed/', max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired / Deleted')], db_index=True, default='QUEUED', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('input_size', models.PositiveIntegerField(default=0, help_text='Input file size in bytes')),
                ('output_size', models.PositiveIntegerField(default=0, help_text='Output file size in bytes')),
                ('error_message', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('file_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_files_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pdf_process_user_id_a9a098_idx'), models.Index(fields=['status'], name='pdf_process_status_0d88a8_idx'), models.Index(fields=['file_expires_at'], name='pdf_process_file_ex_1a618a_idx')],
            },
        ),
    ]
