# Generated by Django 5.2.17 on 2026-10-02 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfprocessingjob',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key during which the PDF was uploaded/processed', max_length=64),
        ),
        migrations.AddIndex(
            model_name='pdfprocessingjob',
            index=models.Index(fields=['session_key'], name='pdf_process_session_cfd1ed_idx'),
        ),
    ]
